version: '3.8'
services:
  app:
    container_name: AHG_backend
    image: ahg-backend
    build: ./
    ports:
      - "8020:8020"
    depends_on:
      - postgresqldb
      - ahgapp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  postgresqldb:
    container_name: postgresDB
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  ahgapp:
    container_name: AHG_frontend
    image: ahg-frontend
    ports:
      - "8080:80"

